// Compresses the two largest static assets that ship with every public
// request:
//   - public/logo.png          (transparent PNG, ~1.6 MB -> ~92 KB)
//   - public/images/hero-bride-groom.jpg  (~888 KB -> ~290 KB)
//   - regenerates lib/hero-blur.ts so the hero's <Image placeholder="blur">
//     stays in sync with the compressed photo.
//
// Re-run after replacing either source file with a higher-resolution master.
//
// Requires the Pillow Python package (already installed in this project).
//   pip install pillow
//
// Usage:
//   python scripts/compress-assets.py

import os
from pathlib import Path
import base64
import io

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]


def _save_optimized(img: Image.Image, dest: Path, *, format: str, **kwargs) -> None:
    img.save(dest, format=format, optimize=True, **kwargs)
    print(f"  {dest.relative_to(ROOT)}: {os.path.getsize(dest):,} bytes")


def compress_logo() -> None:
    src = ROOT / 'public' / 'logo.png'
    img = Image.open(src).convert('RGBA')
    # Logo is rendered at 48-64 CSS px everywhere; 256px is comfortable for
    # 3x retina without making the file larger than it needs to be.
    img.thumbnail((256, 256), Image.LANCZOS)
    print(f'logo.png: compressing from {os.path.getsize(src):,} bytes')
    _save_optimized(img, src, format='PNG')


def compress_hero() -> None:
    src = ROOT / 'public' / 'images' / 'hero-bride-groom.jpg'
    img = Image.open(src).convert('RGB')
    # Hero is shown at most ~46vw on a 1600-px viewport ~= 736 CSS px; 1600
    # is plenty for 2x retina and cuts the source 4x+ on large masters.
    img.thumbnail((1600, 1600), Image.LANCZOS)
    print(f'hero-bride-groom.jpg: compressing from {os.path.getsize(src):,} bytes')
    _save_optimized(img, src, format='JPEG', quality=78, progressive=True)


def emit_hero_blur() -> None:
    # Render a 10x6 LQIP JPEG of the current hero and write a data: URL
    # constant the React tree imports. Keeping this auto-generated makes
    # the blur stay in sync with whatever the source becomes.
    src = ROOT / 'public' / 'images' / 'hero-bride-groom.jpg'
    img = Image.open(src).convert('RGB')
    small = img.copy()
    small.thumbnail((10, 6), Image.LANCZOS)
    buf = io.BytesIO()
    small.save(buf, 'JPEG', quality=40)
    b64 = base64.b64encode(buf.getvalue()).decode('ascii')
    dest = ROOT / 'lib' / 'hero-blur.ts'
    dest.write_text(
        f"""// AUTO-GENERATED by scripts/compress-assets.py. Do not edit by hand.
// 10x6 JPEG low-quality placeholder of /public/images/hero-bride-groom.jpg,
// used as the hero <Image placeholder="blur"> so first paint doesn't show
// an empty frame while the optimized AVIF streams in.

export const HERO_BLUR_DATA_URL =
  'data:image/jpeg;base64,{b64}';
""",
        encoding='utf-8',
    )
    print(f"hero blur data URL: {len(b64)} chars -> {dest.relative_to(ROOT)}")


def main() -> None:
    print('compressing static assets...')
    compress_logo()
    compress_hero()
    emit_hero_blur()
    print('done.')


if __name__ == '__main__':
    main()
